# Generated by Django 5.2.1 on 2025-06-24 13:14

import django.db.models.deletion
import document_emails.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0092_alter_frontendapikey_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('email_service_id', models.CharField(blank=True, help_text='ID from email service provider', max_length=255)),
                ('email_template', models.CharField(blank=True, help_text='Template name used for this email', max_length=100)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_communications', to='core.application')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Communication',
                'verbose_name_plural': 'Email Communications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('spam', 'Marked as Spam'), ('unsubscribed', 'Unsubscribed')], max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('service_data', models.JSONField(blank=True, default=dict, help_text='Raw data from email service webhook')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='document_emails.emailcommunication')),
            ],
            options={
                'verbose_name': 'Email Delivery Log',
                'verbose_name_plural': 'Email Delivery Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmailDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=document_emails.models.get_email_document_file_path)),
                ('original_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_documents', to='document_emails.emailcommunication')),
                ('source_document', models.ForeignKey(blank=True, help_text='Original document this email document was copied from', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.document')),
            ],
            options={
                'verbose_name': 'Email Document',
                'verbose_name_plural': 'Email Documents',
                'ordering': ['created_at'],
            },
        ),
    ]
