# Generated by Django 5.2.1 on 2025-07-23 15:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0105_alter_frontendapikey_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=255)),
                ('application_id', models.CharField(max_length=100)),
                ('total_pages', models.PositiveIntegerField()),
                ('pdf_scale', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(5.0)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready_for_signing', 'Ready for Signing'), ('partially_signed', 'Partially Signed'), ('fully_signed', 'Fully Signed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_signature_documents', to=settings.AUTH_USER_MODEL)),
                ('source_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature_document', to='core.document')),
            ],
            options={
                'verbose_name': 'Signature Document',
                'verbose_name_plural': 'Signature Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSigner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('signer_type', models.CharField(choices=[('applicant', 'Applicant'), ('solicitor', 'Solicitor'), ('custom', 'Custom Signer')], max_length=20)),
                ('access_method', models.CharField(choices=[('portal', 'Portal Access'), ('email', 'Email Link'), ('in_person', 'In-Person Signing')], max_length=20)),
                ('applicant_id', models.CharField(blank=True, max_length=100, null=True)),
                ('solicitor_id', models.CharField(blank=True, max_length=100, null=True)),
                ('solicitor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('has_signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signing_order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signature_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='esignature.signaturedocument')),
            ],
            options={
                'verbose_name': 'Document Signer',
                'verbose_name_plural': 'Document Signers',
                'ordering': ['signing_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SignatureField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_type', models.CharField(choices=[('signature', 'Signature'), ('initials', 'Initials'), ('name', 'Name'), ('textfield', 'Text Field'), ('dateSigned', 'Date Signed')], max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('is_auto_fill', models.BooleanField(default=False)),
                ('page_number', models.PositiveIntegerField()),
                ('x_position', models.FloatField()),
                ('y_position', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('is_signed', models.BooleanField(default=False)),
                ('signed_value', models.TextField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signature_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_fields', to='esignature.signaturedocument')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_fields', to='esignature.documentsigner')),
            ],
            options={
                'verbose_name': 'Signature Field',
                'verbose_name_plural': 'Signature Fields',
                'ordering': ['page_number', 'y_position', 'x_position'],
            },
        ),
    ]
