# Generated by Django 5.2.1 on 2025-06-19 10:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0088_alter_frontendapikey_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_approvers', models.PositiveIntegerField(default=2, help_text='Number of different staff users required to complete the checklist', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Checklist Configuration',
                'verbose_name_plural': 'Checklist Configuration',
            },
        ),
        migrations.CreateModel(
            name='FinanceChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Finance Checklist Item',
                'verbose_name_plural': 'Finance Checklist Items',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LoanChecklistSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('checked_items', models.ManyToManyField(blank=True, to='finance_checklist.financechecklistitem')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_submissions', to='core.loan')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Checklist Submission',
                'verbose_name_plural': 'Loan Checklist Submissions',
                'ordering': ['-submitted_at'],
                'unique_together': {('loan', 'submitted_by')},
            },
        ),
        migrations.CreateModel(
            name='LoanChecklistItemCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_checklist.financechecklistitem')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_checks', to='finance_checklist.loanchecklistsubmission')),
            ],
            options={
                'verbose_name': 'Loan Checklist Item Check',
                'verbose_name_plural': 'Loan Checklist Item Checks',
                'unique_together': {('submission', 'checklist_item')},
            },
        ),
    ]
