# Generated by Django 3.2.25 on 2024-06-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_application_deceased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
