# Generated by Django 3.2.25 on 2024-06-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240619_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
