# Generated by Django 3.2.25 on 2024-06-20 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_estate_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='deceased',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.deceased'),
        ),
    ]
