# Generated by Django 3.2.25 on 2024-07-12 13:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_auto_20240628_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='eircode',
            field=models.CharField(max_length=7, validators=[]),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='pps_number',
            field=models.CharField(error_messages={'max_length': 'Ensure that PPS field has no more than 9 characters'},
                                   max_length=13),
        ),
    ]
