# Generated by Django 3.2.25 on 2024-07-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20240712_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='pps_number',
            field=models.CharField(error_messages={'max_length': 'Ensure that PPS field has no more than 9 characters'}, max_length=9),
        ),
    ]
