# Generated by Django 3.2.25 on 2024-06-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
