# Generated by Django 3.2.25 on 2024-06-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_document_original_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_loan_agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='is_undertaking',
            field=models.BooleanField(default=False),
        ),
    ]
