# Generated by Django 3.2.25 on 2024-08-08 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_applicant_pps_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='loan_agreement_ready',
        ),
        migrations.RemoveField(
            model_name='application',
            name='undertaking_ready',
        ),
    ]
