# Generated by Django 3.2.25 on 2024-06-24 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='application_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.application'),
        ),
    ]
