# Generated by Django 3.2.25 on 2024-06-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_events_application_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='application_id',
            new_name='application',
        ),
    ]
