# Generated by Django 3.2.25 on 2024-08-09 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20240808_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='deceased',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.deceased'),
        ),
        migrations.AlterField(
            model_name='application',
            name='dispute',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application', to='core.dispute'),
        ),
        migrations.AlterField(
            model_name='application',
            name='rejected_reason',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rejectionreason'),
        ),
    ]
