# Generated by Django 3.2.25 on 2024-06-24 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20240624_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='application',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.application'),
        ),
    ]
