# Generated by Django 3.2.25 on 2024-08-09 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20240809_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='deceased',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.deceased'),
        ),
        migrations.AlterField(
            model_name='application',
            name='dispute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.dispute'),
        ),
    ]
