# Generated by Django 3.2.25 on 2024-08-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20240809_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='rejected_reason',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='RejectionReason',
        ),
    ]
