# Generated by Django 3.2.25 on 2024-06-26 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.application')),
            ],
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
