# Generated by Django 3.2.25 on 2024-08-29 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_notification_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedSolicitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('own_email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('own_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
