# Generated by Django 3.2.25 on 2024-08-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_assignedsolicitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedsolicitor',
            name='own_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
