# Generated by Django 3.2.25 on 2024-08-29 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_assignedsolicitor_own_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssignedSolicitor',
            new_name='Solicitor',
        ),
    ]
