# Generated by Django 3.2.25 on 2024-08-29 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_assignedsolicitor_solicitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='solicitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='core.solicitor'),
        ),
    ]
