# Generated by Django 3.2.25 on 2024-09-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_document_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='signeddocumentlog',
            name='signing_user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
