# Generated by Django 3.2.25 on 2024-09-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_signeddocumentlog_signing_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='signeddocumentlog',
            name='confirmation_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signeddocumentlog',
            name='solicitor_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
