# Generated by Django 3.2.25 on 2024-09-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20240930_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='signeddocumentlog',
            name='confirmation_checked_by_user',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
