# Generated by Django 3.2.25 on 2024-10-02 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20241002_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signeddocumentlog',
            old_name='eircode',
            new_name='zip',
        ),
    ]
