# Generated by Django 3.2.25 on 2024-10-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_rename_eircode_signeddocumentlog_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='signeddocumentlog',
            name='is_proxy',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='signeddocumentlog',
            name='proxy_provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='signeddocumentlog',
            name='proxy_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
