# Generated by Django 3.2.25 on 2024-10-02 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20241002_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signeddocumentlog',
            old_name='proxy_type',
            new_name='type',
        ),
    ]
