# Generated by Django 3.2.25 on 2024-10-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_rename_proxy_type_signeddocumentlog_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='signeddocumentlog',
            name='signature_image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
