# Generated by Django 3.2.25 on 2024-10-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20241004_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signeddocumentlog',
            old_name='device_platform',
            new_name='device_model',
        ),
        migrations.AddField(
            model_name='signeddocumentlog',
            name='device_cpu_architecture',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='signeddocumentlog',
            name='device_os_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signeddocumentlog',
            name='device_os_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signeddocumentlog',
            name='device_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='signeddocumentlog',
            name='device_vendor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
