# Generated by Django 3.2.25 on 2024-10-07 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20241004_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(help_text='Agency user assigned to the staff member', limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_staff', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(help_text='Staff user to whom agencies are assigned', limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_agencies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Default Assignment',
                'verbose_name_plural': 'Agent Default Assignments',
                'unique_together': {('staff', 'agency')},
            },
        ),
    ]
