# Generated by Django 3.2.25 on 2024-10-07 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20241007_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='agency_user',
            field=models.OneToOneField(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_staff_user', to='core.user'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='staff_user',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_agencies', to='core.user'),
        ),
    ]
