# Generated by Django 5.1.1 on 2024-10-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='attachments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='original_filenames',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
