# Generated by Django 3.2.25 on 2024-10-10 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_emaillog_attachments_emaillog_original_filenames'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='core.application'),
        ),
    ]
