# Generated by Django 3.2.25 on 2024-10-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_emaillog_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitor',
            name='own_email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
