# Generated by Django 3.2.25 on 2024-10-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_solicitor_own_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
