# Generated by Django 3.2.25 on 2024-10-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_emaillog_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='in_reply_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
