# Generated by Django 3.2.25 on 2024-10-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_emaillog_in_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='references',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
