# Generated by Django 3.2.25 on 2024-10-11 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_emaillog_references'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaillog',
            name='application',
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='in_reply_to',
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='references',
        ),
    ]
