# Generated by Django 3.2.25 on 2024-10-14 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20241011_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.application'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='solicitor_firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
