# Generated by Django 3.2.25 on 2024-10-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_associatedemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
