# Generated by Django 3.2.25 on 2024-10-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_useremaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='send_from',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='useremaillog',
            name='send_from',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
