# Generated by Django 3.2.25 on 2024-11-04 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20241023_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('decision_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='is_committee_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='needs_committee_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['date_submitted'], name='core_applic_date_su_f1e1a8_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['term'], name='core_applic_term_60af1d_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['amount'], name='core_applic_amount_170e1c_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user'], name='core_applic_user_id_c1e2bf_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['solicitor'], name='core_applic_solicit_ffee65_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['assigned_to'], name='core_applic_assigne_0df5fc_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['amount_agreed'], name='core_loan_amount__895a3d_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['fee_agreed'], name='core_loan_fee_agr_710804_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['term_agreed'], name='core_loan_term_ag_64ee38_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['settled_date'], name='core_loan_settled_f5a44e_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['paid_out_date'], name='core_loan_paid_ou_dea2e2_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['is_settled'], name='core_loan_is_sett_f2fb2e_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['is_paid_out'], name='core_loan_is_paid_f4e845_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['is_committee_approved'], name='core_loan_is_comm_6926f6_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['needs_committee_approval'], name='core_loan_needs_c_1fb8ad_idx'),
        ),
        migrations.AddField(
            model_name='committeeapproval',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_approvals', to='core.loan'),
        ),
        migrations.AddField(
            model_name='committeeapproval',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='committeeapproval',
            unique_together={('loan', 'member')},
        ),
    ]
