# Generated by Django 3.2.25 on 2024-11-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20241104_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='is_committee_approved',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
