# Generated by Django 3.2.25 on 2024-11-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_loan_is_committee_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='pay_out_reference_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
