# Generated by Django 5.1.1 on 2024-11-19 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_loan_pay_out_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeeapproval',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='committee_approvals', to='core.application'),
        ),
        migrations.AlterField(
            model_name='committeeapproval',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_approvals', to='core.loan'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['pay_out_reference_number'], name='core_loan_pay_out_3dc2b1_idx'),
        ),
    ]
