# Generated by Django 3.2.25 on 2024-11-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_committeeapproval_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('IE', 'Ireland'), ('UK', 'United Kingdom')], max_length=2, null=True),
        ),
    ]
