# Generated by Django 3.2.25 on 2024-11-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_token',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
    ]
