# Generated by Django 3.2.25 on 2024-12-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20241202_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('IE', 'Ireland (Euro)'), ('UK', 'United Kingdom (Pound)')], max_length=2, null=True),
        ),
    ]
