# Generated by Django 3.2.25 on 2024-12-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_auth_method',
            field=models.CharField(choices=[('otp', 'OTP via Email'), ('authenticator', 'Authenticator App')], default='otp', max_length=20, verbose_name='Preferred Authentication Method'),
        ),
    ]
