# Generated by Django 3.2.25 on 2024-12-05 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_user_preferred_auth_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticatorSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authenticator_secret', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
