# Generated by Django 3.2.25 on 2024-12-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_authenticatorsecret_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
