# Generated by Django 3.2.25 on 2024-12-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitor',
            name='own_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
