# Generated by Django 3.2.25 on 2024-12-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_alter_solicitor_own_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='eircode',
            field=models.CharField(max_length=7),
        ),
    ]
