# Generated by Django 3.2.25 on 2024-12-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_address_eircode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='county',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
