# Generated by Django 3.2.25 on 2024-12-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_alter_address_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
