# Generated by Django 3.2.25 on 2025-02-11 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_application_is_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='ioeOxpt-fGeRVorP8QqkjWMCdKsPM0FOtbs-N1I7AyU', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='frontend_api_key', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
