# Generated by Django 5.2.1 on 2025-06-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_frontendapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='lendable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='frontendapikey',
            name='key',
            field=models.CharField(default='urCCKZSIWwwbI5FQ6wXx7CuO3p16sKcXxs_l8lDvka8', max_length=64, unique=True),
        ),
    ]
