# Generated by Django 5.2.1 on 2025-06-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_estate_lendable_alter_frontendapikey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='lendable',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='frontendapikey',
            name='key',
            field=models.CharField(default='uTzeKxxsxEugptd-E0tSjThuBtX2bnjBBFnqefGGVpU', max_length=64, unique=True),
        ),
    ]
