# Generated by Django 5.2.1 on 2025-06-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_alter_estate_lendable_alter_frontendapikey_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='was_will_prepared_by_solicitor',
            field=models.BooleanField(default=False, help_text='Was this will professionally prepared by a solicitor?'),
        ),
        migrations.AlterField(
            model_name='frontendapikey',
            name='key',
            field=models.CharField(default='cXSGFxRRMNpnfFCIWlRD8MkC2UlUGN4p5k-PO5DjU54', max_length=64, unique=True),
        ),
    ]
