# Generated by Django 5.2.1 on 2025-06-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_application_was_will_prepared_by_solicitor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='description',
        ),
        migrations.AddField(
            model_name='estate',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='estate',
            name='name',
            field=models.CharField(default='BackwardComp', max_length=128),
        ),
        migrations.AlterField(
            model_name='frontendapikey',
            name='key',
            field=models.CharField(default='hWIEDajJp1-6mBOBGzBlvEYh0EBNp0yXeX9-HtPsB_M', max_length=64, unique=True),
        ),
    ]
