# Generated by Django 5.2.1 on 2025-06-10 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_remove_estate_description_estate_details_estate_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendapikey',
            name='key',
            field=models.CharField(default='1_FaeSWyhan5rc7DOLYm3H4eknQ5S2KCpo_a_rK_3Lw', max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='BusinessFarming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lendable', models.BooleanField(default=True)),
                ('is_asset', models.BooleanField(default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_farming', to='core.application')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessOther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lendable', models.BooleanField(default=True)),
                ('is_asset', models.BooleanField(default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_other', to='core.application')),
            ],
        ),
        migrations.CreateModel(
            name='CarsBoats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lendable', models.BooleanField(default=True)),
                ('is_asset', models.BooleanField(default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_boats', to='core.application')),
            ],
        ),
        migrations.CreateModel(
            name='DebtOwed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtor', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lendable', models.BooleanField(default=False)),
                ('is_asset', models.BooleanField(default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts_owing', to='core.application')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, max_length=128)),
                ('account_number', models.CharField(blank=True, max_length=128)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lendable', models.BooleanField(default=True)),
                ('is_asset', models.BooleanField(default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_assets', to='core.application')),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lendable', models.BooleanField(default=True)),
                ('is_asset', models.BooleanField(default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_contents', to='core.application')),
            ],
        ),
        migrations.CreateModel(
            name='IrishDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditor', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_asset', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irish_debts', to='core.application')),
            ],
        ),
        migrations.CreateModel(
            name='LifeInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurer', models.CharField(blank=True, max_length=128)),
                ('policy_number', models.CharField(blank=True, max_length=128)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lendable', models.BooleanField(default=True)),
                ('is_asset', models.BooleanField(default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_insurance', to='core.application')),
            ],
        ),
        migrations.CreateModel(
            name='OtherProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lendable', models.BooleanField(default=True)),
                ('is_asset', models.BooleanField(default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_property', to='core.application')),
            ],
        ),
        migrations.CreateModel(
            name='RealAndLeaseholdProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True)),
                ('county', models.CharField(blank=True, max_length=128)),
                ('nature', models.CharField(blank=True, max_length=128)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lendable', models.BooleanField(default=True)),
                ('is_asset', models.BooleanField(default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_and_leasehold', to='core.application')),
            ],
        ),
        migrations.CreateModel(
            name='SecuritiesQuoted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lendable', models.BooleanField(default=True)),
                ('is_asset', models.BooleanField(default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='securities_quoted', to='core.application')),
            ],
        ),
        migrations.CreateModel(
            name='SecuritiesUnquoted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lendable', models.BooleanField(default=False)),
                ('is_asset', models.BooleanField(default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='securities_unquoted', to='core.application')),
            ],
        ),
        migrations.CreateModel(
            name='UnpaidPurchaseMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lendable', models.BooleanField(default=True)),
                ('is_asset', models.BooleanField(default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unpaid_purchase_money', to='core.application')),
            ],
        ),
        migrations.DeleteModel(
            name='Estate',
        ),
    ]
