# Generated by Django 5.2.1 on 2025-06-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_alter_frontendapikey_key_businessfarming_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='irishdebt',
            name='lendable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='frontendapikey',
            name='key',
            field=models.CharField(default='IWj4qaGIBGR6Vu6KzRo_-OphGNw3aSUfE8mkTuSZAk8', max_length=64, unique=True),
        ),
    ]
