# Generated by Django 5.2.1 on 2025-06-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_irishdebt_lendable_alter_frontendapikey_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AddField(
            model_name='document',
            name='signature_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='who_needs_to_sign',
            field=models.CharField(choices=[('solicitor', 'Solicitor'), ('applicant', 'Applicant')], default='solicitor', help_text='Who needs to sign this document', max_length=20),
        ),
        migrations.AlterField(
            model_name='frontendapikey',
            name='key',
            field=models.CharField(default='2-ZTweWS60Tjkj_Iy6ICKJSicvXvaMsEmVD5K8MVEU8', max_length=64, unique=True),
        ),
    ]
