# Generated by Django 5.2.1 on 2025-06-14 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_alter_document_options_document_signature_required_and_more'),
        ('document_requirements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type_requirement',
            field=models.ForeignKey(blank=True, help_text='The requirement this document fulfills', null=True, on_delete=django.db.models.deletion.SET_NULL, to='document_requirements.applicationdocumentrequirement'),
        ),
        migrations.AlterField(
            model_name='frontendapikey',
            name='key',
            field=models.CharField(default='D_SuSmRpgBONcT_u3TE53a_-eKXsZWKxsjnhcBGjgE8', max_length=64, unique=True),
        ),
    ]
