# Generated by Django 5.2.1 on 2025-06-17 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_alter_applicant_options_applicant_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendapikey',
            name='key',
            field=models.CharField(default='ned85atlkXRVwAwCWSNtU33L5yjisdapLmCjsmFr6To', max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='ApplicationProcessingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_details_completed_confirmed', models.BooleanField(default=False)),
                ('solicitor_preferred_aml_method', models.CharField(blank=True, choices=[('KYC', 'KYC'), ('AML', 'AML')], max_length=3, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processing_status', to='core.application')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_processing_status_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
