# Generated by Django 5.2.1 on 2025-06-18 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_alter_frontendapikey_key_internalfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalfile',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_files', to='core.application'),
        ),
        migrations.AlterField(
            model_name='frontendapikey',
            name='key',
            field=models.CharField(default='aiVmr72oMHBZNlQc9Ao-ZVEjzLojDampdGNqhSVnOeA', max_length=64, unique=True),
        ),
        migrations.AddIndex(
            model_name='internalfile',
            index=models.Index(fields=['application'], name='core_intern_applica_efcc88_idx'),
        ),
        migrations.AddIndex(
            model_name='internalfile',
            index=models.Index(fields=['created_at'], name='core_intern_created_394779_idx'),
        ),
        migrations.AddIndex(
            model_name='internalfile',
            index=models.Index(fields=['is_active'], name='core_intern_is_acti_a19589_idx'),
        ),
    ]
