# Generated by Django 5.2.1 on 2025-06-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_internalfile_application_alter_frontendapikey_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendapikey',
            name='key',
            field=models.CharField(default='sqr2gCdBtIgC5N4cHD6SXFqo7YtC3Hfu5Yz3JO0G9Ew', max_length=64, unique=True),
        ),
    ]
