# Generated by Django 5.2.1 on 2025-06-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_alter_frontendapikey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendapikey',
            name='key',
            field=models.CharField(default='J_0Hu0V96RX-V8QBLFLx9JkHZ9Ra2TlXeMg3qLHnJkA', max_length=64, unique=True),
        ),
    ]
