# Generated by Django 5.2.1 on 2025-06-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_alter_frontendapikey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendapikey',
            name='key',
            field=models.CharField(default='EQTAWNqmJClOcZA-4ydQKt58oEv8yEIRZpqPlkbah8Q', max_length=64, unique=True),
        ),
    ]
