# Generated by Django 5.2.1 on 2025-06-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_alter_frontendapikey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendapikey',
            name='key',
            field=models.CharField(default='jfTf8PPf-1C9uB79EbEb59zfSM9rYP3vW_yEio2BJgg', max_length=64, unique=True),
        ),
    ]
