# Generated by Django 5.2.1 on 2025-06-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_alter_frontendapikey_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalfile',
            name='is_pep_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='frontendapikey',
            name='key',
            field=models.CharField(default='SqG8MZAcgqnI-l9pU56-l8Kh_75NFg3awYgJ4PDgnXw', max_length=64, unique=True),
        ),
        migrations.AddIndex(
            model_name='internalfile',
            index=models.Index(fields=['is_ccr'], name='core_intern_is_ccr_428c05_idx'),
        ),
        migrations.AddIndex(
            model_name='internalfile',
            index=models.Index(fields=['is_pep_check'], name='core_intern_is_pep__896e47_idx'),
        ),
    ]
