# Generated by Django 5.2.1 on 2025-07-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_internalfile_is_pep_check_alter_frontendapikey_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_terms_of_business',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='frontendapikey',
            name='key',
            field=models.CharField(default='xEsaFicQ8rI1tqGK6wI27yYurb2MeEldfYPH9UHObQI', max_length=64, unique=True),
        ),
    ]
