# Generated by Django 5.2.1 on 2025-07-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_document_is_terms_of_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_secci',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='frontendapikey',
            name='key',
            field=models.CharField(default='ZHBriZLMxq5ScKC_K9xIAIEapI2EywR9FbwDLhu6IxI', max_length=64, unique=True),
        ),
    ]
