# Generated by Django 5.2.1 on 2025-07-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_document_is_secci_alter_frontendapikey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendapikey',
            name='key',
            field=models.CharField(default='usAFtc481iFoU5aWlg3-lr8VtrM88Afrm8IHlX5y5dc', max_length=64, unique=True),
        ),
    ]
