# Generated by Django 5.2.1 on 2025-07-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_alter_frontendapikey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendapikey',
            name='key',
            field=models.CharField(default='9uEWAihLNOR4e3ZRJf9XNWH-93E4Fc6ZfU5bvivdpjM', max_length=64, unique=True),
        ),
    ]
