# Generated by Django 5.2.1 on 2025-07-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_alter_frontendapikey_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_manual_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='frontendapikey',
            name='key',
            field=models.CharField(default='oPnFJD0ODbdrjfOq4sbdbScrbj9SgFm7F_JQcD9ULP4', max_length=64, unique=True),
        ),
    ]
