# Generated by Django 5.2.1 on 2025-07-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_document_uploaded_by_alter_frontendapikey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendapikey',
            name='key',
            field=models.CharField(default='r8p8u2B25EjipA7miieQqqYrxJX-Uom1mzVrGNyWAPs', max_length=64, unique=True),
        ),
    ]
