# Generated by Django 5.2.1 on 2025-07-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_alter_frontendapikey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendapikey',
            name='key',
            field=models.CharField(default='H6wC-Dc9xw5GvovDuV9MT-NjV3liiFCi1EIlz0c6qtM', max_length=64, unique=True),
        ),
    ]
