# Generated by Django 5.2.1 on 2025-07-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_alter_frontendapikey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendapikey',
            name='key',
            field=models.CharField(default='8Wyew3mfFCT2Nm8A3FXgqrb7HyPjDZ2ro5ZySsmtfV8', max_length=64, unique=True),
        ),
    ]
