# Generated by Django 5.2.1 on 2025-07-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_alter_frontendapikey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendapikey',
            name='key',
            field=models.CharField(default='17Ku2UZ7gqsMC6rfPsfHZD0MiN0MaEcWIBkk6ilFZe0', max_length=64, unique=True),
        ),
    ]
