# Generated by Django 5.2.1 on 2025-07-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_alter_frontendapikey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendapikey',
            name='key',
            field=models.CharField(default='LJ_fW5nqvrmmx44vpiEils5aNZRyGD7sqJr3URTFI9Q', max_length=64, unique=True),
        ),
    ]
