# Generated by Django 5.2.1 on 2025-07-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_alter_frontendapikey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendapikey',
            name='key',
            field=models.CharField(default='h2RvEsLus5TnjgjoNkX0mMUA3T-OeGrNLtkJFfLBtiw', max_length=64, unique=True),
        ),
    ]
