# Generated by Django 5.2.1 on 2025-07-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_alter_frontendapikey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendapikey',
            name='key',
            field=models.CharField(default='xJ2bEAaUQhRP7zt0PAxL-X-Y_5jLKiThITUxrlzCU2Y', max_length=64, unique=True),
        ),
    ]
