# Generated by Django 5.2.1 on 2025-07-04 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loanbook', '0005_alter_loanbook_daily_fee_after_year_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCRContractRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccr_contract_id', models.CharField(help_text='Internal CCR contract reference', max_length=50)),
                ('first_reported_date', models.DateField()),
                ('last_reported_date', models.DateField()),
                ('is_closed_in_ccr', models.BooleanField(default=False)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('loanbook', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ccr_record', to='loanbook.loanbook')),
            ],
        ),
        migrations.CreateModel(
            name='CCRSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_date', models.DateField(help_text='Month-end date being reported')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(max_length=500)),
                ('total_records', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATED', 'Generated'), ('UPLOADED', 'Uploaded'), ('ACKNOWLEDGED', 'Acknowledged by CCR'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('is_test_submission', models.BooleanField(default=False)),
                ('test_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-reference_date'],
                'unique_together': {('reference_date',)},
            },
        ),
        migrations.CreateModel(
            name='CCRContractSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_type', models.CharField(choices=[('NEW', 'New Contract'), ('UPDATE', 'Monthly Update'), ('SETTLEMENT', 'Final Settlement')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccr_reporting.ccrcontractrecord')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccr_reporting.ccrsubmission')),
            ],
        ),
        migrations.AddField(
            model_name='ccrcontractrecord',
            name='submissions',
            field=models.ManyToManyField(through='ccr_reporting.CCRContractSubmission', to='ccr_reporting.ccrsubmission'),
        ),
        migrations.AlterUniqueTogether(
            name='ccrcontractrecord',
            unique_together={('ccr_contract_id',)},
        ),
    ]
