# Generated by Django 5.2.1 on 2025-07-04 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccr_reporting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ccrsubmission',
            name='ccr_response_file',
            field=models.FileField(blank=True, help_text='Response file from CCR system', null=True, upload_to='ccr_responses/'),
        ),
        migrations.AddField(
            model_name='ccrsubmission',
            name='error_details',
            field=models.TextField(blank=True, help_text='Details of any errors encountered'),
        ),
        migrations.AddField(
            model_name='ccrsubmission',
            name='has_modifications',
            field=models.BooleanField(default=False, help_text='File was modified after generation'),
        ),
        migrations.AddField(
            model_name='ccrsubmission',
            name='modification_notes',
            field=models.TextField(blank=True, help_text='Notes about modifications made'),
        ),
        migrations.AddField(
            model_name='ccrsubmission',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ccrsubmission',
            name='status_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ccrsubmission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('GENERATED', 'Generated'), ('UPLOADED', 'Uploaded'), ('ACKNOWLEDGED', 'Acknowledged by CCR'), ('ERROR', 'Error'), ('PARTIAL_ERROR', 'Partial Error')], default='GENERATED', max_length=20),
        ),
        migrations.CreateModel(
            name='CCRErrorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('VALIDATION', 'Validation Error'), ('MISSING_DATA', 'Missing Data'), ('FORMAT_ERROR', 'Format Error'), ('DUPLICATE', 'Duplicate Record'), ('OTHER', 'Other')], max_length=20)),
                ('error_description', models.TextField()),
                ('line_number', models.IntegerField(blank=True, help_text='Line number in CCR file', null=True)),
                ('original_line_content', models.TextField(blank=True, help_text='Original line that caused error')),
                ('resolution_status', models.CharField(choices=[('PENDING', 'Pending Resolution'), ('FIXED_MANUAL', 'Fixed Manually'), ('FIXED_AUTO', 'Fixed Automatically'), ('CARRIED_FORWARD', 'Carried to Next Submission'), ('IGNORED', 'Ignored')], default='PENDING', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('carry_forward_to', models.ForeignKey(blank=True, help_text='If carried forward, reference to next submission', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ccr_reporting.ccrerrorrecord')),
                ('contract_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ccr_reporting.ccrcontractrecord')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_records', to='ccr_reporting.ccrsubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CCRStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATED', 'Generated'), ('UPLOADED', 'Uploaded'), ('ACKNOWLEDGED', 'Acknowledged by CCR'), ('ERROR', 'Error'), ('PARTIAL_ERROR', 'Partial Error')], max_length=20)),
                ('new_status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATED', 'Generated'), ('UPLOADED', 'Uploaded'), ('ACKNOWLEDGED', 'Acknowledged by CCR'), ('ERROR', 'Error'), ('PARTIAL_ERROR', 'Partial Error')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='ccr_reporting.ccrsubmission')),
            ],
            options={
                'verbose_name_plural': 'CCR Status Histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
