# Generated by Django 5.2.1 on 2025-06-19 22:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0089_alter_frontendapikey_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanBook',
            fields=[
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='loanbook', serialize=False, to='core.loan')),
                ('initial_amount', models.DecimalField(decimal_places=2, help_text='Snapshot of loan.amount_agreed at time of creation', max_digits=14)),
                ('estate_net_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('initial_fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('daily_fee_after_year_percentage', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=5)),
                ('exit_fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
