# Generated by Django 5.2.1 on 2025-06-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanbook',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
