# Generated by Django 5.2.1 on 2025-06-20 13:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanbook', '0002_alter_loanbook_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanbook',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanbook',
            name='daily_fee_after_year_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.07'), max_digits=5),
        ),
    ]
