# Generated by Django 5.2.1 on 2025-07-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanbook', '0003_alter_loanbook_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanbook',
            name='daily_fee_after_year_percentage',
            field=models.DecimalField(decimal_places=2, help_text='Daily fee percentage after first year', max_digits=5),
        ),
        migrations.AlterField(
            model_name='loanbook',
            name='exit_fee_percentage',
            field=models.DecimalField(decimal_places=2, help_text='Exit fee percentage on settlement', max_digits=5),
        ),
        migrations.AlterField(
            model_name='loanbook',
            name='initial_fee_percentage',
            field=models.DecimalField(decimal_places=2, help_text='First year flat fee percentage', max_digits=5),
        ),
    ]
