# Generated by Django 5.2.1 on 2025-07-01 11:37

import loanbook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanbook', '0004_alter_loanbook_daily_fee_after_year_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanbook',
            name='daily_fee_after_year_percentage',
            field=models.DecimalField(decimal_places=2, default=loanbook.models.get_daily_fee_default, help_text='Daily fee percentage after first year', max_digits=5),
        ),
        migrations.AlterField(
            model_name='loanbook',
            name='exit_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=loanbook.models.get_exit_fee_default, help_text='Exit fee percentage on settlement', max_digits=5),
        ),
        migrations.AlterField(
            model_name='loanbook',
            name='initial_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=loanbook.models.get_initial_fee_default, help_text='First year flat fee percentage', max_digits=5),
        ),
    ]
