# Generated by Django 5.2.1 on 2025-06-14 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0081_alter_document_options_document_signature_required_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description shown to users')),
                ('signature_required', models.BooleanField(default=False)),
                ('who_needs_to_sign', models.CharField(blank=True, choices=[('solicitor', 'Solicitor'), ('applicant', 'Applicant')], help_text='Who needs to sign this document (if signature required)', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requirements', to='core.application')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who added this requirement', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_requirements.documenttype')),
            ],
            options={
                'verbose_name': 'Application Document Requirement',
                'verbose_name_plural': 'Application Document Requirements',
                'ordering': ['document_type__order', 'document_type__name'],
                'unique_together': {('application', 'document_type')},
            },
        ),
    ]
