# Generated by Django 5.2.1 on 2025-07-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_requirements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='has_template',
            field=models.BooleanField(default=False, help_text='Whether this document type should auto-generate a template document'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='template_fields',
            field=models.JSONField(blank=True, default=dict, help_text='JSON mapping of template placeholders to application data fields'),
        ),
    ]
